.TH "oyranos-config-synnefo(1)" "April 05, 2017" "oyranos-config-synnefo"
.SH NAME
oyranos-config-synnefo \- Color Management Configuration.
.SH SYNOPSIS
\fBoyranos-config-synnefo\fR
.SH DESCRIPTION
.I "oyranos-config-synnefo"
uses the Oyranos CMS to provide the ability to set and examine device profiles, as well as to change system-wide color settings.
.SH ENVIRONMENT
.TP
.B DISPLAY
On X11 systems the display is selected by this variable.
.SH AUTHOR
Joseph Simon - main author
Kai-Uwe Behrmann (ku.b (at) gmx.de) - maintainer
.SH "SEE ALSO"
oyranos-config-fltk(1) oyranos(3)
.SH BUGS
at: http://sourceforge.net/tracker/?group_id=177017&atid=879553
