#############################################################################
# Makefile for building: synnefo
# Generated by qmake (2.01a) (Qt 4.6.3) on: Tue Mar 8 21:39:32 2011
# Project:  synnefo.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile synnefo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -L/usr/lib64 -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = synnefo.cpp \
		main.cpp moc_synnefo.cpp
OBJECTS       = synnefo.o \
		main.o \
		moc_synnefo.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		synnefo.pro
QMAKE_TARGET  = synnefo
DESTDIR       = 
TARGET        = synnefo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_syfoMain.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: synnefo.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -unix -o Makefile synnefo.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile synnefo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/synnefo1.0.0 || $(MKDIR) .tmp/synnefo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/synnefo1.0.0/ && $(COPY_FILE) --parents synnefo.h .tmp/synnefo1.0.0/ && $(COPY_FILE) --parents synnefo.cpp main.cpp .tmp/synnefo1.0.0/ && $(COPY_FILE) --parents syfoMain.ui .tmp/synnefo1.0.0/ && (cd `dirname .tmp/synnefo1.0.0` && $(TAR) synnefo1.0.0.tar synnefo1.0.0 && $(COMPRESS) synnefo1.0.0.tar) && $(MOVE) `dirname .tmp/synnefo1.0.0`/synnefo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/synnefo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_synnefo.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_synnefo.cpp
moc_synnefo.cpp: ui_syfoMain.h \
		synnefo.h
	/usr/bin/moc $(DEFINES) $(INCPATH) synnefo.h -o moc_synnefo.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_syfoMain.h
compiler_uic_clean:
	-$(DEL_FILE) ui_syfoMain.h
ui_syfoMain.h: syfoMain.ui
	/usr/bin/uic syfoMain.ui -o ui_syfoMain.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

synnefo.o: synnefo.cpp synnefo.h \
		ui_syfoMain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o synnefo.o synnefo.cpp

main.o: main.cpp synnefo.h \
		ui_syfoMain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_synnefo.o: moc_synnefo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_synnefo.o moc_synnefo.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib64/qt4/examples/bin/synnefo/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib64/qt4/examples/bin/synnefo/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/lib64/qt4/examples/bin/synnefo/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/lib64/qt4/examples/bin/synnefo/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib64/qt4/examples/bin/synnefo/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib64/qt4/examples/bin/synnefo/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib64/qt4/examples./ || $(MKDIR) $(INSTALL_ROOT)/usr/lib64/qt4/examples./ 
	-$(INSTALL_FILE) /home/joe/Work/Synnefo/synnefo.cpp $(INSTALL_ROOT)/usr/lib64/qt4/examples./
	-$(INSTALL_FILE) /home/joe/Work/Synnefo/main.cpp $(INSTALL_ROOT)/usr/lib64/qt4/examples./
	-$(INSTALL_FILE) /home/joe/Work/Synnefo/synnefo.h $(INSTALL_ROOT)/usr/lib64/qt4/examples./
	-$(INSTALL_FILE) /home/joe/Work/Synnefo/syfoMain.ui $(INSTALL_ROOT)/usr/lib64/qt4/examples./
	-$(INSTALL_FILE) /home/joe/Work/Synnefo/synnefo.pro $(INSTALL_ROOT)/usr/lib64/qt4/examples./


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib64/qt4/examples./synnefo.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib64/qt4/examples./main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib64/qt4/examples./synnefo.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib64/qt4/examples./syfoMain.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib64/qt4/examples./synnefo.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib64/qt4/examples./ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

